"""empty message

Revision ID: 28218815bf84
Revises: be7c7355cb36
Create Date: 2025-05-06 01:31:50.388304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28218815bf84'
down_revision = 'be7c7355cb36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_skills')
    # ### end Alembic commands ###
