"""empty message

Revision ID: 3ab3faf80157
Revises: 26c30f047e06
Create Date: 2025-05-03 20:31:15.944382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ab3faf80157'
down_revision = '26c30f047e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('career', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('education')
        batch_op.drop_column('location')
        batch_op.drop_column('language')
        batch_op.drop_column('career')

    # ### end Alembic commands ###
