"""empty message

Revision ID: 4dd275d33d2d
Revises: 087801f698b0
Create Date: 2025-05-08 23:14:16.080354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd275d33d2d'
down_revision = '087801f698b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_reviewer_proposal', ['reviewer_id', 'proposal_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('uix_reviewer_proposal', type_='unique')

    # ### end Alembic commands ###
