"""empty message

Revision ID: 564203afdd7d
Revises: 3577031205cb
Create Date: 2025-05-04 21:19:39.259636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564203afdd7d'
down_revision = '3577031205cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
