"""empty message

Revision ID: 654357242aad
Revises: 28218815bf84
Create Date: 2025-05-08 05:52:31.120519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654357242aad'
down_revision = '28218815bf84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
