"""empty message

Revision ID: 909e213ed416
Revises: ed1572e1c4b1
Create Date: 2025-05-13 13:03:38.618355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909e213ed416'
down_revision = 'ed1572e1c4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
