"""empty message

Revision ID: bfa4260f4e7c
Revises: 7cf4c9473544
Create Date: 2025-05-03 19:58:45.099335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa4260f4e7c'
down_revision = '7cf4c9473544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('career', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('education', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('education')
        batch_op.drop_column('location')
        batch_op.drop_column('language')
        batch_op.drop_column('career')

    # ### end Alembic commands ###
